const SUPABASE_URL='https://yivgtvgyaalhlcxatbfc.supabase.co';
const SUPABASE_KEY='sb_publishable_JSNYdrq-FFHQtZ0DO3sfVw_v93KOBjs';
const ADMIN='theoccosta2020@gmail.com';
const LOGO='logo.svg';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let user=null,profile=null,current='geral',pendingEmail='',pendingImage=null,pendingAvatar=null,msgSub=null;
let profiles=new Map(),roles=new Map(),memberRoles=new Map(),signed=new Map();
let room=null,stream=null,presenceSub=null,signalSub=null,beat=null,peers=new Map(),ice=new Map(),muted=false;
const textChannels=[
{id:'geral',name:'Geral',desc:'Conversa geral da Creative Squad.',private:false,adminSend:false},
{id:'administracao',name:'Administração',desc:'Área privada da administração.',private:true,adminSend:true},
{id:'reunioes',name:'Reuniões Administrativas',desc:'Área privada para reuniões administrativas.',private:true,adminSend:true},
{id:'comunicados',name:'Comunicados',desc:'Comunicados oficiais.',private:false,adminSend:true},
{id:'carregadoria',name:'Carregadoria da CS',desc:'Canal oficial da Carregadoria.',private:false,adminSend:true},
{id:'judiciario',name:'Poder Judiciário CS',desc:'Canal oficial do Poder Judiciário.',private:false,adminSend:true}
];
const voiceRooms=[
{id:'voz-geral',name:'Geral • Voz',private:false},{id:'voz-minecraft',name:'Minecraft • Voz',private:false},{id:'voz-administracao',name:'Administração • Voz',private:true},{id:'voz-reunioes',name:'Reuniões • Voz',private:true}
];
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const admin=()=>user&&String(user.email).toLowerCase()===ADMIN;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function loginMsg(t){$('loginMsg').textContent=t||''}
async function sendCode(resend=false){const email=resend?pendingEmail:$('email').value.trim();if(!email.includes('@'))return loginMsg('Digite um e-mail válido.');pendingEmail=email;loginMsg('Enviando código...');const {error}=await sb.auth.signInWithOtp({email,options:{shouldCreateUser:true}});if(error)return loginMsg('Erro: '+error.message);$('emailStep').classList.add('hidden');$('codeStep').classList.remove('hidden');$('codeEmail').textContent=email;$('code').value='';loginMsg('Código enviado para seu e-mail.');}
function changeEmail(){$('codeStep').classList.add('hidden');$('emailStep').classList.remove('hidden');loginMsg('')}
async function verifyCode(){const token=$('code').value.trim();if(token.length<6)return loginMsg('Digite o código recebido.');loginMsg('Verificando...');const {data,error}=await sb.auth.verifyOtp({email:pendingEmail,token,type:'email'});if(error||!data.user)return loginMsg('Código inválido ou expirado.');user=data.user;await ensureProfile();await welcome();enter();}
async function welcome(){$('verify').classList.remove('hidden');$('verifyContent').innerHTML='<div class="icon">✅</div><h2>VERIFICADO</h2><p>E-mail confirmado.</p>';await sleep(900);$('verifyContent').innerHTML='<div class="icon">⏳</div><h2>Entrando...</h2>';await sleep(850);$('verifyContent').innerHTML='<div class="icon">🎮</div><h2>Bem-vindo de volta,<br>'+esc((profile?.display_name||'Membro').toUpperCase())+'!!</h2>';await sleep(1500);$('verify').classList.add('hidden')}
async function restore(){const {data}=await sb.auth.getSession();if(data.session?.user){user=data.session.user;await ensureProfile();enter();}}
async function logout(){await leaveVoice();if(msgSub)await sb.removeChannel(msgSub);await sb.auth.signOut();location.reload()}
async function ensureProfile(){const {data}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(data)profile=data;else{const e=user.email.toLowerCase(),base=e.split('@')[0],name=e===ADMIN?'Theo':base.replace(/[._-]/g,' ').replace(/\b\w/g,x=>x.toUpperCase());const {data:d,error}=await sb.from('profiles').insert({id:user.id,email:e,display_name:name,nickname:base,bio:'Membro verificado da Creative Squad'}).select().single();if(error)throw error;profile=d;}await caches();}
async function caches(){const [{data:p},{data:r},{data:m}]=await Promise.all([sb.from('profiles').select('*'),sb.from('roles').select('*').order('id'),sb.from('member_roles').select('*')]);profiles=new Map((p||[]).map(x=>[x.id,x]));roles=new Map((r||[]).map(x=>[x.id,x]));memberRoles=new Map();(m||[]).forEach(x=>{if(!memberRoles.has(x.user_id))memberRoles.set(x.user_id,[]);const rr=roles.get(x.role_id);if(rr)memberRoles.get(x.user_id).push(rr)});if(profile)profiles.set(profile.id,profile);}
function enter(){$('login').classList.add('hidden');$('app').classList.remove('hidden');$('rolesTab').classList.toggle('hidden',!admin());renderChannels();renderVoices();renderProfile();selectChannel('geral');tab('home');}
function tab(t){if(t==='roles'&&!admin())t='home';['home','chat','profile','roles'].forEach(x=>$(x).classList.toggle('hidden',x!==t));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));if(t==='chat'){renderChannels();renderVoices();selectChannel(current)}if(t==='profile')renderProfile();if(t==='roles'){rolePreview();renderRoles();renderMembers();}}
async function url(bucket,path){if(!path)return LOGO;const k=bucket+'|'+path;if(signed.has(k))return signed.get(k);const {data}=await sb.storage.from(bucket).createSignedUrl(path,3600);const u=data?.signedUrl||LOGO;signed.set(k,u);return u}
async function upload(bucket,file,prefix){const ext=(file.name.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'');const path=user.id+'/'+prefix+'-'+Date.now()+'.'+ext;const {error}=await sb.storage.from(bucket).upload(path,file,{contentType:file.type});if(error)throw error;return path}
async function renderProfile(){if(!profile)return;const a=await url('avatars',profile.avatar_path);$('avatar').src=a;$('avatar2').src=a;$('displayName').textContent=profile.display_name;$('displayName2').textContent=profile.display_name;$('profileEmail').textContent=profile.email;$('name').value=profile.display_name;$('nick').value=profile.nickname;$('bio').value=profile.bio||'';$('bio2').textContent=profile.bio||'';$('myRoles').innerHTML=badges(memberRoles.get(user.id)||[]);$('homeName').textContent=profile.display_name;$('homeBio').textContent=profile.bio||'';$('homeRoles').innerHTML=badges(memberRoles.get(user.id)||[])}
function chooseAvatar(e){const f=e.target.files?.[0];if(!f)return;if(f.size>4*1024*1024)return alert('Foto muito grande. Máximo 4 MB.');pendingAvatar=f;const u=URL.createObjectURL(f);$('avatar').src=u;$('avatar2').src=u}
async function saveProfile(){try{let path=profile.avatar_path;if(pendingAvatar)path=await upload('avatars',pendingAvatar,'avatar');const {data,error}=await sb.from('profiles').update({display_name:$('name').value.trim()||profile.display_name,nickname:$('nick').value.trim()||'membro',bio:$('bio').value.trim(),avatar_path:path}).eq('id',user.id).select().single();if(error)throw error;profile=data;pendingAvatar=null;signed.clear();await caches();await renderProfile();await renderMessages();alert('Perfil salvo.')}catch(e){alert(e.message)}}
function roleHtml(r){const c=r.color||'#7cff35',cls=r.style==='rainbow'?'rb rainbow':r.style==='pulse'?'rb pulse':r.style==='neon'?'rb neon':'rb',style=r.style==='rainbow'?'':`color:${c};background:${c}22`;return `<span class="${cls}" style="${style}">${esc(r.name)}</span>`}
function badges(a){return a?.length?a.map(roleHtml).join(' '):'<span class="small">Sem cargos</span>'}
function rolePreview(){$('rolePreview').innerHTML=roleHtml({name:$('roleName')?.value||'Novo Cargo',style:$('roleStyle')?.value||'solid',color:$('roleColor')?.value||'#7cff35'})}
$('roleName')?.addEventListener('input',rolePreview);$('roleStyle')?.addEventListener('change',rolePreview);$('roleColor')?.addEventListener('input',rolePreview);
async function createRole(){if(!admin())return;const name=$('roleName').value.trim();if(!name)return alert('Digite um nome.');const {error}=await sb.from('roles').insert({name,style:$('roleStyle').value,color:$('roleColor').value,created_by:user.id});if(error)return alert(error.message);$('roleName').value='';await caches();renderRoles();renderMembers();await renderMessages();}
function renderRoles(){const a=[...roles.values()];$('roleList').innerHTML=a.length?a.map(r=>`<div class="roleItem"><div class="row between">${roleHtml(r)}<button class="btn danger" onclick="deleteRole(${r.id})">Excluir</button></div></div>`).join(''):'<p class="small">Nenhum cargo.</p>'}
async function deleteRole(id){if(!admin()||!confirm('Excluir cargo?'))return;await sb.from('roles').delete().eq('id',id);await caches();renderRoles();renderMembers();await renderMessages()}
async function renderMembers(){if(!admin())return;const {data}=await sb.from('profiles').select('*').order('display_name');let h='';for(const p of data||[]){const rs=memberRoles.get(p.id)||[],available=[...roles.values()].filter(r=>!rs.some(x=>x.id===r.id));h+=`<div class="member"><b>${esc(p.display_name)}</b><div class="small">${esc(p.email)}</div><div>${badges(rs)}</div><div class="row"><select id="rs_${p.id}"><option value="">Escolher cargo...</option>${available.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select><button class="btn green" onclick="assignRole('${p.id}')">Dar cargo</button></div>${rs.map(r=>`<button class="btn dark" onclick="removeRole('${p.id}',${r.id})">Remover ${esc(r.name)}</button>`).join(' ')}</div>`}$('memberList').innerHTML=h||'<p class="small">Nenhum membro.</p>'}
async function assignRole(id){const rid=Number($('rs_'+id).value);if(!rid)return;const {error}=await sb.from('member_roles').insert({user_id:id,role_id:rid,assigned_by:user.id});if(error)return alert(error.message);await caches();renderMembers();await renderMessages();await renderProfile()}
async function removeRole(id,rid){await sb.from('member_roles').delete().eq('user_id',id).eq('role_id',rid);await caches();renderMembers();await renderMessages();await renderProfile()}
function visibleChannels(){return textChannels.filter(c=>!c.private||admin())}
function renderChannels(){$('channels').innerHTML=visibleChannels().map(c=>`<button class="channel ${c.id===current?'active':''}" onclick="selectChannel('${c.id}')"># ${esc(c.name)}${c.adminSend?'<span class="lock">🔒</span>':''}</button>`).join('')}
async function selectChannel(id){const c=textChannels.find(x=>x.id===id);if(!c)return;if(c.private&&!admin())return alert('Canal privado.');current=id;renderChannels();$('chTitle').textContent='# '+c.name;$('chDesc').textContent=c.desc;$('perm').textContent=c.adminSend?'Somente Theo envia':'Verificados podem enviar';$('composer').classList.toggle('hidden',c.adminSend&&!admin());$('readonly').classList.toggle('hidden',!(c.adminSend&&!admin()));$('readonly').textContent='🔒 Somente '+ADMIN+' pode enviar neste canal.';clearImage();$('stickers').classList.add('hidden');await subscribeMessages()}
async function subscribeMessages(){if(msgSub)await sb.removeChannel(msgSub);await renderMessages();msgSub=sb.channel('m-'+current+'-'+Date.now()).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'channel_id=eq.'+current},async()=>{await caches();await renderMessages()}).subscribe()}
async function renderMessages(){const {data,error}=await sb.from('messages').select('*').eq('channel_id',current).order('created_at').limit(250);if(error)return $('messages').innerHTML='<div class="small">Sem acesso.</div>';let h='';for(const m of data||[]){const p=profiles.get(m.user_id)||{display_name:'Membro CS'},a=await url('avatars',p.avatar_path),im=m.image_path?await url('chat-media',m.image_path):'',time=new Date(m.created_at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});h+=`<div class="m"><img class="av" src="${esc(a)}"><div><div class="mh"><b>${esc(p.display_name)}</b>${badges(memberRoles.get(m.user_id)||[])}<time>${time}</time></div>${m.text?`<div class="mt">${esc(m.text)}</div>`:''}${m.sticker?`<div class="st">${esc(m.sticker)}</div>`:''}${im?`<img class="mi" src="${esc(im)}">`:''}</div></div>`}$('messages').innerHTML=h||'<div class="small">Ainda não há mensagens.</div>';$('messages').scrollTop=$('messages').scrollHeight}
function toggleStickers(){$('stickers').classList.toggle('hidden')}
function chooseImage(e){const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024)return alert('Imagem muito grande. Máximo 8 MB.');pendingImage=f;$('previewImg').src=URL.createObjectURL(f);$('preview').classList.remove('hidden')}
function clearImage(){pendingImage=null;$('preview').classList.add('hidden');$('imgInput').value=''}
async function sendMessage(){const c=textChannels.find(x=>x.id===current);if(c.adminSend&&!admin())return;const text=$('message').value.trim();if(!text&&!pendingImage)return;try{let path=null;if(pendingImage)path=await upload('chat-media',pendingImage,'msg');const {error}=await sb.from('messages').insert({channel_id:current,user_id:user.id,text:text||null,image_path:path,sticker:null});if(error)throw error;$('message').value='';clearImage();await renderMessages()}catch(e){alert(e.message)}}
async function sticker(s){const c=textChannels.find(x=>x.id===current);if(c.adminSend&&!admin())return;const {error}=await sb.from('messages').insert({channel_id:current,user_id:user.id,sticker:s});if(error)alert(error.message);$('stickers').classList.add('hidden')}
$('message')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});
function visibleVoices(){return voiceRooms.filter(r=>!r.private||admin())}
function renderVoices(){$('voices').innerHTML=visibleVoices().map(r=>`<button class="voice ${room===r.id?'joined':''}" onclick="joinVoice('${r.id}')">🔊 ${esc(r.name)}${r.private?'<span class="lock">🔒</span>':''}</button>`).join('')}
async function joinVoice(id){const r=voiceRooms.find(x=>x.id===id);if(r.private&&!admin())return alert('Voz privada.');if(room===id)return;await leaveVoice();try{stream=await navigator.mediaDevices.getUserMedia({audio:true})}catch{return alert('Permita o microfone.')}room=id;muted=false;$('voiceDock').classList.remove('hidden');$('voiceTitle').textContent='🔊 '+r.name;$('voiceStatus').textContent='Conectando...';renderVoices();presenceSub=sb.channel('vp-'+id+'-'+Date.now()).on('postgres_changes',{event:'*',schema:'public',table:'voice_presence',filter:'room=eq.'+id},async p=>{if(p.eventType==='DELETE'&&p.old?.user_id)dropPeer(p.old.user_id);await people()}).subscribe();signalSub=sb.channel('vs-'+id+'-'+Date.now()).on('postgres_changes',{event:'INSERT',schema:'public',table:'voice_signals',filter:'room=eq.'+id},async p=>{const s=p.new;if(s.sender!==user.id&&(!s.target||s.target===user.id))await handleSignal(s)}).subscribe();await sleep(250);const {error}=await sb.from('voice_presence').upsert({user_id:user.id,room:id,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error){alert(error.message);return leaveVoice()}await people();const cutoff=new Date(Date.now()-90000).toISOString();const {data}=await sb.from('voice_presence').select('user_id').eq('room',id).gt('updated_at',cutoff);for(const x of data||[])if(x.user_id!==user.id)await offer(x.user_id);beat=setInterval(()=>room&&sb.from('voice_presence').update({updated_at:new Date().toISOString()}).eq('user_id',user.id),25000);$('voiceStatus').textContent='Conectado'}
async function leaveVoice(){if(beat){clearInterval(beat);beat=null}for(const id of [...peers.keys()])dropPeer(id);if(room&&user)try{await sb.from('voice_presence').delete().eq('user_id',user.id)}catch{}if(presenceSub){await sb.removeChannel(presenceSub);presenceSub=null}if(signalSub){await sb.removeChannel(signalSub);signalSub=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}room=null;ice.clear();$('voiceDock').classList.add('hidden');$('audios').innerHTML='';renderVoices()}
function toggleMute(){if(!stream)return;muted=!muted;stream.getAudioTracks().forEach(t=>t.enabled=!muted);$('mute').textContent=muted?'🔇 Ativar microfone':'🎙️ Mutar'}
function pc(id){if(peers.has(id))return peers.get(id);const p=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream?.getTracks().forEach(t=>p.addTrack(t,stream));p.onicecandidate=e=>e.candidate&&signal(id,{type:'candidate',candidate:e.candidate.toJSON()});p.ontrack=e=>{let a=$('a_'+id);if(!a){a=document.createElement('audio');a.id='a_'+id;a.autoplay=true;a.playsInline=true;$('audios').appendChild(a)}a.srcObject=e.streams[0]};p.onconnectionstatechange=()=>['failed','closed','disconnected'].includes(p.connectionState)&&dropPeer(id);peers.set(id,p);return p}
async function offer(id){const p=pc(id),o=await p.createOffer();await p.setLocalDescription(o);await signal(id,{type:'offer',sdp:o.sdp})}
async function signal(target,signal){await sb.from('voice_signals').insert({room,sender:user.id,target,signal})}
async function handleSignal(row){const id=row.sender,s=row.signal||{},p=pc(id);try{if(s.type==='offer'){await p.setRemoteDescription({type:'offer',sdp:s.sdp});await flush(id,p);const a=await p.createAnswer();await p.setLocalDescription(a);await signal(id,{type:'answer',sdp:a.sdp})}else if(s.type==='answer'){await p.setRemoteDescription({type:'answer',sdp:s.sdp});await flush(id,p)}else if(s.type==='candidate'){if(p.remoteDescription)await p.addIceCandidate(s.candidate);else{if(!ice.has(id))ice.set(id,[]);ice.get(id).push(s.candidate)}}}catch(e){console.warn(e)}}
async function flush(id,p){for(const c of ice.get(id)||[])try{await p.addIceCandidate(c)}catch{}ice.set(id,[])}
function dropPeer(id){const p=peers.get(id);if(p)try{p.close()}catch{}peers.delete(id);$('a_'+id)?.remove()}
async function people(){if(!room)return;const cutoff=new Date(Date.now()-90000).toISOString(),{data}=await sb.from('voice_presence').select('user_id').eq('room',room).gt('updated_at',cutoff);$('voicePeople').innerHTML=(data||[]).map(x=>`<span>🎙️ ${esc(profiles.get(x.user_id)?.display_name||'Membro CS')}</span>`).join('')||'<span>Somente você.</span>'}
rolePreview();restore();